MODEL_NAME = "aisingapore/Llama-SEA-LION-v2-8B"
MAX_TOKENS = 8000
MIN_WORDS = 5
MIN_TOKENS = 5
OCRT_MEAN_THRESHOLD = 0.5
OCRT_SD_THRESHOLD = 0.35
SEPARATOR_TOKEN = "<|end_of_text|>"
# SHARDS = 10
#for test
SHARDS = 1
BATCH_SIZE = 10000
